### PR TITLE
New meetup & fix: Olomouc February 2019 & January 'backport' update

### PR DESCRIPTION
**Pull request by fivaldi**
@JanBednarik or @mcurlej ?

Díky!

### CODE REVIEW

**Comment by JanBednarik** [comment]
@encukou Seems like false positive CI fail. Maybe test requirements are missing versions and broke after some package update?

**Comment by encukou** [comment]
Exactly that. Sorry for the hiccup. Fixed in https://github.com/pyvec/pyvo-data/pull/209 and rebased this PR.

**Comment by encukou** [comment]
Live @ https://pyvo.cz/olomouc-pyvo/

**Comment by JanBednarik** [comment]
Thank you :-)

**Pull request merged**
