### PR TITLE
Use a venue note in Plzeň, Praha, Brno.

### PR DESCRIPTION
**Pull request by encukou**
This depends on https://github.com/pyvec/pyvo.cz/pull/76 to actually show up.

### CODE REVIEW

**Comment by hroncok** [comment]
There are `venue-notes` used all over the place (such as https://github.com/pyvec/pyvo-data/blob/275b794c7bb6561a87d2b5306788298c487c797e/series/brno-pyvo/events/2012-12-17-vetesnictvi.yaml#L9).

There is even se `notes` by a talk at https://github.com/pyvec/pyvo-data/blob/275b794c7bb6561a87d2b5306788298c487c797e/series/praha-pyvo/events/2012-09-19.yaml#L12

Why the renaming from notes to note?

**Comment by encukou** [comment]
An event's `venue-notes` should be specific to an event, e.g. which room is used for that particular meetup. It would be nice to support these as well, I guess. They were imported from Lanyrd.

A talk's `coverage/notes` is for a link to the speaker's notes.

> Why the renaming from notes to note?

It seemed like a good idea to not use an existing name when assigning more specific semantics. Now I don't think it was such a good idea, but I also don't think it's really worth changing back.

**Comment by hroncok** [comment]
> Now I don't think it was such a good idea, but I also don't think it's really worth changing back.

It brings inconsistency. My OCD screams. But I won't fight you if you decide to keep it.

**Comment by encukou** [comment]
OK, I'll change it back, during the weekend.

**Pull request merged**
