### PR TITLE
Build status

### PR DESCRIPTION
**Pull request by frenzymadness**
Rename README to README.md and add build status icon to it.

### CODE REVIEW

**Comment by frenzymadness** [comment]
The build is failing because there is a new unknown file README.md.
I have prepared PR for [pyvodb](https://github.com/pyvec/pyvodb) but I don't have access rights to create a new branch in the pyvodb repository.

**Comment by encukou** [comment]
I think it's better to use personal forks for pull requests, instead of creating branches in the main repository.

BTW, it would be nice to put the list of ignored files in `meta.yaml`, so syncing pyvodb would not be needed when a new file to ignore appears.

**Comment by frenzymadness** [comment]
I've prepared PR to load ignored_files from `meta.yaml` here: https://github.com/pyvec/pyvodb/pull/2
I've also added a list of ignored files to meta.yaml in the last commit.
The best will be to merge mentioned PR first and then rerun tests here.

**Comment by frenzymadness** [comment]
I've just realized that pyvodb is installed via pip so it will need to make a new version and publish it on PyPI to make tests in this PR pass.

**Comment by encukou** [comment]
Yeah. I have another fix almost ready, and plan to release once that's in.

**Comment by encukou** [comment]
The other fix is in https://github.com/pyvec/pyvodb/pull/3

**Comment by encukou** [comment]
https://github.com/pyvec/pyvo-data/pull/30

**Pull request merged**
