### PR TITLE
Ostrava: New city, venue and event

### PR DESCRIPTION
**Pull request by frenzymadness**

### CODE REVIEW

**Comment by encukou** [comment]
Fixed YAML syntax and some typos, and merged.
The typos are still on srazy info; please update there :)

**Comment by frenzymadness** [comment]
Could you please point me to the typos?

**Comment by encukou** [comment]
Oops, my bad; I merged your version. Fix-up commit at fc29c27.

**Comment by encukou** [comment]
pořádká → pořádná
nevyspytatelného → nevyzpytatelného

**Pull request closed without merging**
