### PR TITLE
Add January meetup for Brno

### PR DESCRIPTION
**Pull request by encukou**

### CODE REVIEW

**Comment by apophys** [comment]
Aside from broken build, ack.

**Comment by hroncok** [comment]
Restarting Travis build.

**Comment by hroncok** [comment]
fatal: unable to access 'https://github.com/pyvec/pyvo-data.git/': Failed to connect to github.com port 443: Connection timed out

well, I guess we'll never know if it builds :D

**Comment by encukou** [comment]
oh no

**Comment by encukou** [comment]
it builds! https://pyvo.cz/brno-pyvo/2018-01/

**Pull request merged**
